{
 "title": "Triton Inference",
 "description": "Dashboard for Triton inference server",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Model",
    "label": "Model",
    "query": {
     "query": "label_values(nv_inference_request_success,model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inference Request Latency p90",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_request_summary_us{model=~\"$Model\", quantile=\"0.9\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Compute Time by Model (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_compute_infer_duration_us[30s])) by (model) / 1000",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_request_success{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}} - success"
    },
    {
     "expr": "max by (job,model)(irate(nv_inference_request_failure{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}} - failure"
    }
   ]
  },
  {
   "title": "Model inference rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_count{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Triton Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (job)(nv_pinned_memory_pool_total_bytes)",
     "legendFormat": "{{job}} - Total memory"
    },
    {
     "expr": "max by (job)(nv_pinned_memory_pool_used_bytes)",
     "legendFormat": "{{job}} - Used memory"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "# max by (job,model)(irate(nv_inference_queue_duration_us{model=~\"$Model\"}[1m]))\nrate(nv_inference_queue_duration_us{model=~\"$Model\"}[30s]) / (1+rate(nv_inference_request_success{model=~\"$Model\"}[30s]))\n# avg(rate(nv_inference_queue_duration_us{model=~\"$Model\"}[30s])/(1+rate(nv_inference_request_success{model=~\"$Model\"}[30s])))",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nv_gpu_utilization*100", "legendFormat": "GPU {{gpu_uuid}}" }
   ]
  },
  {
   "title": "GPU Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_gpu_memory_used_bytes", "legendFormat": "GPU {{gpu_uuid}}" },
    { "expr": "nv_gpu_memory_total_bytes", "legendFormat": "GPU {{gpu_uuid}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nv_cpu_utilization * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_cpu_memory_used_bytes", "legendFormat": "Used" },
    { "expr": "nv_cpu_memory_total_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Compute input duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_compute_input_duration_us{model=~\"$Model\"}[1m]))\n",
     "legendFormat": "{{job}} - {{model}}"
    }
   ]
  },
  {
   "title": "Compute output duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (job,model)(irate(nv_inference_compute_output_duration_us{model=~\"$Model\"}[1m]))",
     "legendFormat": "{{job}} - {{model}}"
    },
    { "expr": "nv", "legendFormat": "__auto" }
   ]
  }
 ]
}