name: "PP-LCNet_doc_ori"
platform: "tensorrt_plan"
max_batch_size: 8
default_model_filename: "doc_ori.plan"

input [
  {
    name: "x"       
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "fetch_name_0"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 2
  }
]
